name: "document-suite"

networks:
  document-network:
    driver: bridge

# volumes:
# minio_data: null
# rustfs_data: null
# rustfs_logs: null
# pg_data: null
# temporal_data: null
# qdrant_data: null

services:
  # --- WORKFLOW ENGINE ----
  workflows:
    build:
      context: ./workflow
    container_name: workflow
    networks: [document-network]
    depends_on:
      - temporal
      - postgres
      - mlflow
      - rustfs
      - qdrant
    environment:
      AWS_REGION: ${AWS_REGION}
      RUSTFS_PORT: ${RUSTFS_PORT}
      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      TEMPORAL_NAMESPACE: default
      
      POSTGRES_ADDRESS: ${POSTGRES_CONTAINER_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB} # TODO - change to its own databse based on migration {POSTGRES_WORKFLOW_DB}
      
      RUSTFS_ADDRESS: ${RUSTFS_CONTAINER_NAME}
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      WORKFLOW_PORT: ${WORKFLOW_PORT}

      DOCUMENT_S3_BUCKET: ${DOCUMENT_S3_BUCKET}
    ports:
      - "${WORKFLOW_PORT}:${WORKFLOW_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "/bin/sh",
          "-c",
          "wget -qO- http://localhost:${WORKFLOW_PORT}/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    container_name: ${TEMPORAL_CONTAINER_NAME}
    networks: [document-network]
    # volumes:
    #   - temporal_data:/etc/temporal/config/dynamicconfig
    depends_on:
      - ${POSTGRES_CONTAINER_NAME}
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      POSTGRES_SEEDS: postgres # TODO : find out what this means
      # DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      TEMPORAL_CLI_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233

  # temporal-admin-tools:
  #   image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
  #   container_name: temporal-admin-tools
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT}
  #     - TEMPORAL_CLI_ADDRESS=temporal:${TEMPORAL_PORT}
  #   stdin_open: true
  #   tty: true

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    container_name: temporal-ui
    networks: [document-network]
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      # TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "${TEMPORAL_UI_PORT}:8080"

  ocr:
    build:
      context: ocr-services/tesseract
    container_name: ocr
    environment:
      OCR_ADDRESS: ${OCR_ADDRESS}

  mlflow:
    # TODO - use a dedicated postgres database instead of maindb
    image: ghcr.io/mlflow/mlflow:${MLFLOW_VERSION}
    networks: [document-network]
    container_name: mlflow
    # volumes:
    #   - # TODO
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_healthy
      rustfs-create-bucket:
        condition: service_completed_successfully
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}

      AWS_ACCESS_KEY_ID: ${RUSTFS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${RUSTFS_SECRET_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      MLFLOW_S3_IGNORE_TLS: "true" # TODO

      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    command:
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir psycopg2-binary boto3
        mlflow server \
          --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} \
          --artifacts-destination ${MLFLOW_ARTIFACTS_DESTINATION} \
          --serve-artifacts \
          --host ${MLFLOW_HOST} \
          --port ${MLFLOW_PORT}

# ------------------------------------ ------------------------------------


# ------------------------------------ STORAGE ------------------------------------

  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    networks: [document-network]
    container_name: qdrant
    # ports:
    #   - "${QDRANT_PORT}:6333"
    # volumes:
    #   - qdrant_data:/qdrant/

  postgres:
    image: postgres:12
    container_name: ${POSTGRES_CONTAINER_NAME}
    networks: [document-network]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
    # volumes:
    #   - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  rustfs:
    image: rustfs/rustfs:${RUSTFS_VERSION}
    container_name: ${RUSTFS_CONTAINER_NAME}
    networks: [document-network]
    ports:
      # - "${RUSTFS_PORT}:${RUSTFS_PORT}"
      - "${RUSTFS_CONSOLE_PORT}:${RUSTFS_CONSOLE_PORT}"
    # volumes:
    #   - rustfs_data:/data
    #   - rustfs_logs:/app/logs
    # (missing) tls cert mount
    environment:
      RUSTFS_ADDRESS: ${RUSTFS_HOST}:${RUSTFS_PORT}
      RUSTFS_CONSOLE_ADDRESS: ${RUSTFS_HOST}:${RUSTFS_CONSOLE_PORT}
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: ${RUSTFS_CONSOLE_ENABLE}

      # - RUSTFS_VOLUMES=/data/rustfs{0..3} # Define 4 storage volumes

      # - RUSTFS_SERVER_DOMAINS

      # - RUSTFS_CORS_ALLOWED_ORIGINS=*
      # - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*

      # - RUSTFS_OBS_LOGGER_LEVEL=info
      # - RUSTFS_OBS_ENDPOINT=http://otel-collector:4317

      # - RUSTFS_TLS_PATH=/opt/tls
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:${RUSTFS_PORT}/health && curl -f http://localhost:${RUSTFS_CONSOLE_PORT}/rustfs/console/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


# ------------------------------------ INITIALIZATION ------------------------------------

  rustfs-create-bucket:
    image: minio/mc:${MINIO_MC_VERSION}
    networks: [document-network]
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set rustfs http://${RUSTFS_CONTAINER_NAME}:${RUSTFS_PORT} "${RUSTFS_ACCESS_KEY}" "${RUSTFS_SECRET_KEY}"
        mc mb --ignore-existing "rustfs/${MLFLOW_ARTIFACT_S3_BUCKET}"
        mc mb --ignore-existing "rustfs/${DOCUMENT_S3_BUCKET}"
    restart: "no"

  # TODO
  # user init for pg


  # TODO
  # postgres-migration:
  #   # TODO - use a dedicated postgres database instead of maindb
  #   build:
  #     context: ./migration
  #   container_name: migration
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   restart: "no"



# ------------------------------------ SYSTEM MONITOR ------------------------------------

  # rabbitmq:
  #   image: rabbitmq:${RABBITMQ_VERSION}
  #   ports:
  #     - "5672:5672"
  #     - "15692:15692"
  #   environment:
  #     - RABITMQ_DEFAULT_USER=ROOT
  #     - RABITMQ_DEFAULT_PASS=ROOT1234

# prometheus:
#   image: prom/prometheus:latest
#   ports:
#     - "9090:9090"
#   volumes:
#     - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

# grafana

# alertmanager:
#   image: prom/alertmanager:latest
#   depends_on:
#     - prometheus
#   ports:
#     - "9093:9093"
#   volumes:
#     - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
#   entrypoint: ["alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]
